apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: demo-blue-green
spec:
  hosts:
  - "demo-blue-green"
  http:
  - route:
    - destination:
        host: demo-blue-green
        subset: production
      weight: {{ .Values.vs.prodductionWeight }}
    - destination:
        host: demo-blue-green
        subset: canary
      weight: {{ .Values.vs.canaryWeight }}
